### ISSUE TITLE
Great Work! A question about the dataset.

### ISSUE THREAD

**Issue by jiahuanluo** [lipiji/DRGD-LCSTS#1]
Thanks for your job! I wonder how to **download the prepared dataset used in (Rush et al., 2015)** .  I hope you would agree to share the dataset with us. Thanks!

**Comment by jiahuanluo** [comment]
About the Gigaword dataset used in the paper.

**Comment by lipiji** [comment]
You can download the dataset from: https://github.com/harvardnlp/sent-summary

**Comment by jiahuanluo** [comment]
Thanks! But how do you split the dataset into training, validation, and testing? The dataset in https://github.com/harvardnlp/sent-summary does not contain the testing data. Should I split it randomly?

**Comment by lipiji** [comment]
All the training, validating, and testing data are in the packages. Please check it again.
